pub const UFS_BRASIL: [&str; 27] = [
    "AC", "AL", "AP", "AM", "BA",
    "CE", "DF", "ES", "GO", "MA",
    "MT", "MS", "MG", "PA", "PB",
    "PR", "PE", "PI", "RJ", "RN",
    "RS", "RO", "RR", "SC", "SP",
    "SE", "TO",
];

pub fn mapa_ufs_br_dados() -> Vec<(&'static str, Vec<&'static str>)> {
    vec![
        ("010", vec!["DF", "GO", "TO", "MA", "PA"]),
        ("020", vec!["DF", "GO", "BA", "PI", "CE"]),
        ("030", vec!["DF", "GO", "MG", "BA"]),
        ("040", vec!["DF", "GO", "MG", "RJ"]),
        ("050", vec!["DF", "GO", "MG", "SP"]),
        ("060", vec!["DF", "GO", "MS"]),
        ("070", vec!["DF", "GO", "MT"]),
        ("080", vec!["DF", "GO", "MT"]),
        ("101", vec!["RN", "PB", "PE", "AL", "SE", "BA", "ES", "RJ", "SP", "PR", "SC", "RS"]),
        ("104", vec!["RN", "PB", "PE", "AL"]),
        ("110", vec!["RN", "PB", "PE", "AL", "BA"]),
        ("116", vec!["CE", "PB", "PE", "BA", "MG", "RJ", "SP", "PR", "SC", "RS"]),
        ("122", vec!["CE", "PE", "BA", "MG"]),
        ("135", vec!["MA", "PI", "BA", "MG"]),
        ("153", vec!["PA", "TO", "GO", "MG", "SP", "PR", "SC", "RS"]),
        ("158", vec!["PA", "MT", "GO", "MS", "SP", "PR", "SC", "RS"]),
        ("163", vec!["PA", "MT", "MS", "PR", "SC", "RS"]),
        ("174", vec!["MT", "RO", "AM", "RR"]),
        ("222", vec!["CE", "PI", "MA", "PA"]),
        ("226", vec!["RN", "CE", "PI", "MA", "TO"]),
        ("230", vec!["PB", "CE", "PI", "MA", "TO", "PA", "AM"]),
        ("232", vec!["PE"]),
        ("235", vec!["SE", "BA", "PE", "PI", "MA", "TO", "PA"]),
        ("242", vec!["BA", "TO", "MT"]),
        ("251", vec!["BA", "MG", "DF", "GO", "MT"]),
        ("262", vec!["ES", "MG", "SP", "MS"]),
        ("267", vec!["MG", "SP", "MS"]),
        ("272", vec!["SP", "PR"]),
        ("277", vec!["PR"]),
        ("280", vec!["SC"]),
        ("282", vec!["SC"]),
        ("285", vec!["SC", "RS"]),
        ("290", vec!["RS"]),
        ("293", vec!["RS"]),
        ("304", vec!["RN", "CE"]),
        ("316", vec!["PA", "MA", "PI", "PE", "AL"]),
        ("319", vec!["AM", "RO"]),
        ("324", vec!["BA"]),
        ("343", vec!["PI"]),
        ("364", vec!["SP", "MG", "GO", "MT", "RO", "AC"]),
        ("365", vec!["MG"]),
        ("369", vec!["MG", "SP", "PR"]),
        ("376", vec!["PR", "MS"]),
        ("381", vec!["ES", "MG", "SP"]),
        ("386", vec!["RS", "SC"]),
        ("392", vec!["RS"]),
        ("405", vec!["RN", "PB"]),
        ("406", vec!["RN"]),
        ("407", vec!["PI", "PE", "BA"]),
        ("427", vec!["RN", "PB"]),
        ("453", vec!["RS"]),
        ("470", vec!["SC", "RS"]),
        ("471", vec!["RS"]),
    ]
}

pub fn operadoras_padrao_dados() -> Vec<(&'static str, Vec<&'static str>)> {
    vec![
        ("CLARO", vec!["CLARO"]),
        ("VIVO", vec!["TELEFONICA", "TELEFÔNICA", "VIVO"]),
        ("TIM", vec!["TIM"]),
        ("BRISANET", vec!["BRISANET"]),
        ("ALGAR", vec!["ALGAR"]),
        ("UNIFIQUE", vec!["UNIFIQUE"]),
    ]
}

pub fn cores_kml_dados() -> Vec<(&'static str, &'static str)> {
    vec![
        ("VIVO", "ff990099"),
        ("CLARO", "ff0000ff"),
        ("TIM", "ffff6600"),
        ("BRISANET", "ff0080ff"),
        ("OUTRA", "ff00ff00"),
    ]
}

/// Lista de `(regex, substituicao)` — porta 1:1 de `_SUBSTITUICOES_BAIRROS`.
pub fn substituicoes_bairros_dados() -> Vec<(&'static str, &'static str)> {
    vec![
        (r"\bN\.?\s*SRA\.?\b", "NOSSA SENHORA"),
        (r"\bNOSSA\s+SRA\.?\b", "NOSSA SENHORA"),
        (r"\bN\.?\s*S\.?\s+(?=[DAEO]\b)", "NOSSA SENHORA "),
        (r"\bSTA\b\.?", "SANTA"),
        (r"\bSTO\b\.?", "SANTO"),
        (r"\bS\.?\s+(?=[A-ZÀ-Ÿ]{3,})", "SÃO "),
        (r"\bJD\b\.?", "JARDIM"),
        (r"\bJRD\b\.?", "JARDIM"),
        (r"\bJARDIN\b", "JARDIM"),
        (r"\bPQ\b\.?", "PARQUE"),
        (r"\bPRQ\b\.?", "PARQUE"),
        (r"\bVL\b\.?", "VILA"),
        (r"\bCJ\b\.?", "CONJUNTO"),
        (r"\bCONJ\b\.?", "CONJUNTO"),
        (r"\bCONJ\.?\s*HAB\b\.?", "CONJUNTO HABITACIONAL"),
        (r"\bCOHAB\b", "CONJUNTO HABITACIONAL"),
        (r"\bLOT\b\.?", "LOTEAMENTO"),
        (r"\bRES\b\.?", "RESIDENCIAL"),
        (r"\bRESID\b\.?", "RESIDENCIAL"),
        (r"\bCHAC\b\.?", "CHÁCARA"),
        (r"\bBALN\b\.?", "BALNEÁRIO"),
        (r"\bBAL\b\.?", "BALNEÁRIO"),
        (r"\bDIST\.?\s*IND\.?\b", "DISTRITO INDUSTRIAL"),
        (r"\bD\.?\s*I\.?\b", "DISTRITO INDUSTRIAL"),
        (r"\bSET\.?\s*IND\.?\b", "SETOR INDUSTRIAL"),
        (r"\bZ\.?\s*RURAL\b", "ZONA RURAL"),
        (r"\bA\.?\s*RURAL\b", "ZONA RURAL"),
        (r"\bAREA\s+RURAL\b", "ZONA RURAL"),
        (r"\bÁREA\s+RURAL\b", "ZONA RURAL"),
        (r"\bPRES\b\.?", "PRESIDENTE"),
        (r"\bGOV\b\.?", "GOVERNADOR"),
        (r"\bSEN\b\.?", "SENADOR"),
        (r"\bDEP\b\.?", "DEPUTADO"),
        (r"\bMAL\b\.?", "MARECHAL"),
        (r"\bGEN\b\.?", "GENERAL"),
        (r"\bCEL\b\.?", "CORONEL"),
        (r"\bBRIG\b\.?", "BRIGADEIRO"),
        (r"\bPROF\b\.?", "PROFESSOR"),
        (r"\bENG\b\.?", "ENGENHEIRO"),
        (r"\bDR\b\.?", "DOUTOR"),
        (r"\bDRA\b\.?", "DOUTORA"),
        (r"\bPE\b\.?", "PADRE"),
        (r"\bMONS\b\.?", "MONSENHOR"),
        (r"\bALM\b\.?", "ALMIRANTE"),
        (r"\bVISC\b\.?", "VISCONDE"),
        (r"\bMARQ\b\.?", "MARQUÊS"),
        (r"\bAPRESENTCAO\b", "APRESENTAÇÃO"),
        (r"\bAPRESENTACAO\b", "APRESENTAÇÃO"),
        (r"\bCONCEICAO\b", "CONCEIÇÃO"),
        (r"\bASSUNCAO\b", "ASSUNÇÃO"),
        (r"\bCONSOLACAO\b", "CONSOLAÇÃO"),
        (r"\bABOLICAO\b", "ABOLIÇÃO"),
        (r"\bLIBERTACAO\b", "LIBERTAÇÃO"),
        (r"\bREDENCAO\b", "REDENÇÃO"),
        (r"\bRESSURREICAO\b", "RESSURREIÇÃO"),
        (r"\bRENASCENCA\b", "RENASCENÇA"),
        (r"\bESPERANCA\b", "ESPERANÇA"),
        (r"\bBONANCA\b", "BONANÇA"),
        (r"\bALIANCA\b", "ALIANÇA"),
        (r"\bMUDANCA\b", "MUDANÇA"),
        (r"\bCRIANCA\b", "CRIANÇA"),
        (r"\bSAO\b", "SÃO"),
        (r"\bJOAO\b", "JOÃO"),
        (r"\bJOSE\b", "JOSÉ"),
        (r"\bINES\b", "INÊS"),
        (r"\bMONICA\b", "MÔNICA"),
        (r"\bLUCIA\b", "LÚCIA"),
        (r"\bCECILIA\b", "CECÍLIA"),
        (r"\bEFIGENIA\b", "EFIGÊNIA"),
        (r"\bIFIGENIA\b", "IFIGÊNIA"),
        (r"\bSEBASTIAO\b", "SEBASTIÃO"),
        (r"\bCRISTOVAO\b", "CRISTÓVÃO"),
        (r"\bSIMAO\b", "SIMÃO"),
        (r"\bDAMIAO\b", "DAMIÃO"),
        (r"\bANTONIO\b", "ANTÔNIO"),
        (r"\bGERONIMO\b", "GERÔNIMO"),
        (r"\bJERONIMO\b", "JERÔNIMO"),
        (r"\bLOURENCO\b", "LOURENÇO"),
        (r"\bGONCALO\b", "GONÇALO"),
        (r"\bUNIAO\b", "UNIÃO"),
        (r"\bESTACAO\b", "ESTAÇÃO"),
        (r"\bFUNDACAO\b", "FUNDAÇÃO"),
        (r"\bAVIACAO\b", "AVIAÇÃO"),
        (r"\bAMERICA\b", "AMÉRICA"),
        (r"\bBRASILIA\b", "BRASÍLIA"),
        (r"\bVITORIA\b", "VITÓRIA"),
        (r"\bGLORIA\b", "GLÓRIA"),
        (r"\bINDEPENDENCIA\b", "INDEPENDÊNCIA"),
        (r"\bPROVIDENCIA\b", "PROVIDÊNCIA"),
        (r"\bUNIVERSITARIO\b", "UNIVERSITÁRIO"),
        (r"\bINDUSTRIARIO\b", "INDUSTRIÁRIOS"),
        (r"\bCOMERCIO\b", "COMÉRCIO"),
        (r"\bCENTENARIO\b", "CENTENÁRIO"),
        (r"\bBANCARIOS\b", "BANCÁRIOS"),
        (r"\bFUNCIONARIOS\b", "FUNCIONÁRIOS"),
        (r"\bOPERARIOS\b", "OPERÁRIOS"),
        (r"\bFERROVIARIOS\b", "FERROVIÁRIOS"),
        (r"\bDESCOBERT\b", "DESCOBERTA"),
        (r"\bCIDADE\s+DA\s+ESPE\b", "CIDADE DA ESPERANÇA"),
        (r"\bCIDADE\s+ESPERANCA\b", "CIDADE DA ESPERANÇA"),
        (r"\bCIDADE\s+ESPERANÇA\b", "CIDADE DA ESPERANÇA"),
        (r"\bPARQUE\s+DUNAS\b", "PARQUE DAS DUNAS"),
        (r"\bDIX\s SEPT\s ROSADO\b", "DIX-SEPT ROSADO"),
        (r"^DIX[\s\-]*SEPT$", "DIX-SEPT ROSADO"),
        (r"\bRENDINHA\b", "REDINHA"),
    ]
}
